### ISSUE TITLE
invalid url for new feed freezes the app

### ISSUE THREAD

**Issue by Danfro** [nicolascolla/headline#4]
If I enter a invalid url when adding a new feed the app freezes. There is no UI interaction possible anymore. Nothing in the log.
An example for an invalid url is a typo in https -> htrps.

**Comment by nicolascolla** [comment]
I can't seem to reproduce the bug on my end. When I add a nonsensical feed like "asiuhfiushdf" the app keeps loading forever but nothing freezes.

Can you give me the url(s) that give you this issue?

**Comment by Danfro** [comment]
:thinking: Strange. I did not write down the urls, but I am almost sure htrps://ubports.com (the mentioned typo) did make it freeze. Although my first try was some nonsense url. I obviously don' remember. ;-)

Nonetheless, I can NOT reproduce it myself too anymore. Maybe it was a temporary failure of some other sort.

I will close this now and reopen if I have a proper "broken" url to reproduce.

**Comment by nicolascolla** [comment]
I have experienced this when adding a feed without the "https://" part. I relaunched and added it again and it didn't freeze. But it seems like sometimes it does crash.
